### ISSUE TITLE
Binding problem

### ISSUE THREAD

**Issue by IndiceDev** [Ilhasoft/data-binding-validator#1]
Hi,

I'm new to Android Studio and I'm having some trouble with the data binding. I did all the steps on the ReadMe file and still can't make it work.

Corretc me if I'm wrong, but I need to add this to my layout right?

`<layout xmlns:android="http://schemas.android.com/apk/res/android">
<data>
<variable name="androidvalidation"
type="com.github.Ilhasoft:data-binding-validator:0.6.1"/>
</data>
</layout>`

So then I can use the `app:validateMinLength="@{4}"`.

Thank you!

**Comment by johncordeiro** [comment]
Hey @IndiceDev, you need to add `compile 'com.github.Ilhasoft:data-binding-validator:0.6.1'` into your `build.gradle` file, in this case, you are adding to your XML layout.

In order to use inside your XML layout, see this example: https://github.com/Ilhasoft/data-binding-validator/blob/master/sample/src/main/res/layout/activity_main.xml

I'm closing this issue because it's more a doubt about data binding usage and dependency configuration and not a library issue.
